### ISSUE TITLE
sidebar menu: transparency issues

### ISSUE THREAD

**Issue by tuxayo** [maproulette/maproulette2#79] opened 2016-05-27 09:23 UTC
When I open http://maproulette.org:8080/map/-1/1331
And I do nothing else except moving my mouse to the sidebar menu.
Then I see see

![capture d ecran_2016-05-27_11-20-30](https://cloud.githubusercontent.com/assets/2678215/15603803/27d8ae3e-23fd-11e6-9ca6-de8429713f65.png)

On Firefox 46 and Chromium 50

**Comment by mgcuthbert** [comment] 2016-05-27 15:11
This is a duplicate of Issue #62. So closing as duplicate.

**Closed by mgcuthbert** 2016-05-27 15:11 UTC
