### ISSUE TITLE
Starting a challenge does nor work

### ISSUE THREAD

**Issue by ksetdekov** [maproulette/maproulette2#233] opened 2016-12-09 11:00 UTC
After the maproulette.org redesign, clicking "start" on a challenge does nothing.
Expected behavior: launch challenge.
I am using Chrome 54.0.2840.99 m (64-bit) on windows 7 and windows 10.
Screenshot attached:
![screenshot](https://cloud.githubusercontent.com/assets/16122863/21046555/53152272-be16-11e6-8444-578786a2a770.png)

**Comment by mvexel** [comment] 2016-12-09 19:56
I cannot reproduce this with Chrome on Mac.
Could you try again? (I redeployed with minor changes recently)

Could you see if this is reproducible:
* In other browsers
* With a different challenge

Thanks

**Comment by ksetdekov** [comment] 2016-12-12 19:02
I've tested with microsoft Edge and everything works. On a different windows PC with Chrome, the same problem apears. Seems to be related to Chrome on PC.

**Comment by ksetdekov** [comment] 2016-12-12 20:16
Huh!
The issues seems to be AdBlock related.
After I disabled it for http://maproulette.org/, everything started working.
Is this an issue worth considering or should I just close this thread?

**Comment by mvexel** [comment] 2017-03-03 19:58
let's close it for now. Thanks for reporting!

**Closed by mvexel** 2017-03-03 19:58 UTC
Labels: P2
