### ISSUE TITLE
KO: Invalid task status supplied

### ISSUE THREAD

**Issue by habi** [maproulette/maproulette2#230] opened 2016-12-02 16:34 UTC
I'm using maproulette2 on FireFox 50.0.1 on Windows.
After working on one task, I want to skip the next task, which does not work.
I get the error message in the title of this issue or as shown in the attached image.

![clipboard01](https://cloud.githubusercontent.com/assets/1651235/20841797/65d04e48-b8b5-11e6-8826-c585351c30bb.png)

After this error message the site does not work anymore for me.
I.e. when I reload it, I'm signed out and have to sign in with OSM again...

**Comment by mgcuthbert** [comment] 2016-12-05 18:58
This is a duplicate of issue #192

**Closed by mgcuthbert** 2016-12-05 18:58 UTC
Labels: backend, BACKLOG

**Comment by habi** [comment] 2016-12-05 19:42
Sorry for the noise...

**Comment by mgcuthbert** [comment] 2016-12-05 21:32
No worries at all, good to see people reporting things. Don't ever hesitate to write a bug if you feel it is one.
